services:
  # Streamlit Web Service
  - type: web
    name: tradingagents-cn
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python start_render.py"
    healthCheckPath: /_stcore/health
    autoDeploy: true

    # Environment variables (will be set via Render dashboard or API)
    envVars:
      - key: PORT
        value: 8501
      - key: PYTHON_VERSION
        value: 3.11.13
      - key: PYTHONUNBUFFERED
        value: 1

      # AI Model API Keys
      - key: DASHSCOPE_API_KEY
        value: sk-e0100915b5394da0aa8e852bf09d9db8
      - key: DEEPSEEK_API_KEY
        value: sk-43e5588b2aa547c9b977b374b45ddd37
      - key: DEEPSEEK_BASE_URL
        value: https://api.deepseek.com
      - key: DEEPSEEK_ENABLED
        value: true
      - key: SILICONFLOW_API_KEY
        value: sk-goeenxldkpvuywhlgkwdqpzwzgodenvmpxprwluvgolrbzul

      # Financial Data API Keys
      - key: FINNHUB_API_KEY
        value: d372ms9r01qtvbtjrefgd372ms9r01qtvbtjreg0
      - key: TAVILY_API_KEY
        value: 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
      - key: ALPHAVANTAGE_API_KEY
        value: 5DGMRPMMEUBMX7PU
      - key: POLYGON_API_KEY
        value: hb0TuTgFLB603Xtyg_ephpjMpVc8W18L

      # Configuration
      - key: DEFAULT_CHINA_DATA_SOURCE
        value: akshare
      - key: TRADINGAGENTS_LOG_LEVEL
        value: INFO
      - key: MEMORY_ENABLED
        value: true
      - key: MONGODB_ENABLED
        value: false
      - key: REDIS_ENABLED
        value: false
      - key: ENABLE_COST_TRACKING
        value: true
      - key: USE_MONGODB_STORAGE
        value: false

    # Build and runtime settings
    buildFilter:
      paths:
        - "!synology-deploy/**"
        - "!data/**"
        - "!logs/**"
        - "!cache/**"
        - "!tests/**"
        - "!docs/**"
        - "!scripts/**"
        - "!upstream_contribution/**"
        - "!data_backup_*/**"
        - "!.git/**"
        - "!node_modules/**"

  # Redis Service (optional, for session management and caching)
  - type: redis
    name: tradingagents-redis
    plan: free
    ipAllowList: []  # Only allow internal connections

version: "1"